# Site settings
title: gogoprog's blog
email: gogoprog@gmail.com
description: "A code about blog, uh... a blog about code, linux and game development"
baseurl: ""
url: "http://gogopr.org/"
twitter_username: gogoprog
github_username:  gogoprog

# Build settings
markdown: kramdown
permalink: pretty
